export const menus = [
    {
         title: 'Home',
         url: '/pages/home',
         icon: 'fa fa-home',
         enable: true,
         id: -1,
         parent: -1,
     },
       {
         title: 'Dashboard',
         icon: 'fa fa-home',
         url: '/pages/dashboard',
         id: '154',
         parent: -1,
         enable: true,
       },
       {
         title: 'Departemen',
         icon: 'fa fa-industry',
         url: '/list/departemen',
         id: '342',
         parent: -1,
         enable: true,
       },
       {
         title: 'Data Proyek',
         icon: 'fa fa-road',
         url: '/list/proyek',
         id: '17',
         parent: -1,
         enable: true,
       },
       {
         title: 'Man Power',
         icon: 'fa fa-users',
         id: 67,
         parent: -1,
         enable: true,
         children: [ 
           {
             title: 'Data Man Power',
             url: '/list/pekerja',
             id: 14,
             parent: 67,
             enable: true,
           },
           {
             title: 'Cetak QR Code',
             url: '/pages/cetakqr',
             id: 152,
             parent: 67,
             enable: true,
           },
           {
             title: 'History Pekerja Proyek',
             url: '/list/h_proyek',
             id: 166,
             parent: 67,
             enable: true,
           },
           {
             title: 'Setup Status Bekerja',
             url: '/list/data_status_bekerja',
             id: 476,
             parent: 67,
             enable: true,
           },
           ],
         },
       {
         title: 'Kesehatan Pekerja',
         icon: 'fa fa-medkit ',
         id: 560,
         parent: -1,
         enable: true,
         children: [ 
           {
             title: 'Log Kesehatan Pekerja',
             url: '/list/data_kesehatan_pekerja',
             id: 475,
             parent: 560,
             enable: true,
           },
           {
             title: 'Setup Gejala',
             url: '/list/data_gejala',
             id: 474,
             parent: 560,
             enable: true,
           },
           {
             title: 'Setup Riwayat Perjalanan',
             url: '/list/data_m_riwayat_perjalanan',
             id: 477,
             parent: 560,
             enable: true,
           },
           {
             title: 'Setup Syarat Bekerja',
             url: '/list/data_setup_psbb',
             id: 662,
             parent: 560,
             enable: true,
           },
           {
             title: 'Data Master Tempat Tinggal',
             url: '/list/data_m_tempat_tinggal',
             id: 660,
             parent: 560,
             enable: true,
           },
           {
             title: 'Data Master Penyakit',
             url: '/list/data_m_penyakit',
             id: 663,
             parent: 560,
             enable: true,
           },
           {
             title: 'Data Master Status Kesehatan',
             url: '/list/data_m_status_kesehatan',
             id: 661,
             parent: 560,
             enable: true,
           },
           ],
         },
       {
         title: 'Presensi Pekerja',
         icon: 'fa fa-calendar',
         id: 341,
         parent: -1,
         enable: true,
         children: [ 
           {
             title: 'Rekap Presensi',
             url: '/list/hitung_presensi',
             id: 163,
             parent: 341,
             enable: true,
           },
           {
             title: 'Raw Presensi',
             url: '/list/presensi',
             id: 156,
             parent: 341,
             enable: true,
           },
           ],
         },
       {
         title: 'Sub Kontraktor',
         icon: 'fa fa-briefcase',
         id: 232,
         parent: -1,
         enable: true,
         children: [ 
           {
             title: 'Data Subkon',
             url: '/list/subkon',
             id: 344,
             parent: 232,
             enable: true,
           },
           {
             title: 'Kontrak Subkon',
             url: '/list/kontrak_subkon',
             id: 173,
             parent: 232,
             enable: true,
           },
           ],
         },
       {
         title: 'Peralatan',
         icon: 'fa fa-wrench',
         id: 233,
         parent: -1,
         enable: true,
         children: [ 
           {
             title: 'Data Alat',
             url: '/list/alat',
             id: 169,
             parent: 233,
             enable: true,
           },
           {
             title: 'Nama Alat',
             url: '/list/nama_alat',
             id: 178,
             parent: 233,
             enable: true,
           },
           ],
         },
       {
         title: 'Download',
         icon: 'fa fa-download',
         id: 107,
         parent: -1,
         enable: true,
         children: [ 
           {
             title: 'Dokumen',
             url: '/list/dokumen',
             id: 75,
             parent: 107,
             enable: true,
           },
           {
             title: 'Kategori',
             url: '/list/kat_dok',
             id: 76,
             parent: 107,
             enable: true,
           },
           ],
         },
       {
         title: 'Cek Kelengkapan',
         icon: 'fa fa-check',
         id: 471,
         parent: -1,
         enable: true,
         children: [ 
           {
             title: 'Foto KTP',
             url: '/list/vnoktp',
             id: 352,
             parent: 471,
             enable: true,
           },
           {
             title: 'Foto Diri',
             url: '/list/vnofoto',
             id: 353,
             parent: 471,
             enable: true,
           },
           {
             title: 'Rating',
             url: '/list/vnorating',
             id: 354,
             parent: 471,
             enable: true,
           },
           {
             title: 'No Telepon',
             url: '/list/vnotelepon',
             id: 355,
             parent: 471,
             enable: true,
           },
           {
             title: 'Semua kolom',
             url: '/list/vkelengkapan',
             id: 345,
             parent: 471,
             enable: true,
           },
           ],
         },
       {
         title: 'System',
         icon: 'fa fa-cog',
         id: 303,
         parent: -1,
         enable: true,
         children: [ 
           {
             title: 'Pengguna',
             url: '/list/users',
             id: 22,
             parent: 303,
             enable: true,
           },
           {
             title: 'Level Pengguna',
             url: '/list/userlevels',
             id: 21,
             parent: 303,
             enable: true,
           },
           {
             title: 'Mobile App Roles',
             url: '/list/mobile_roles',
             id: 168,
             parent: 303,
             enable: true,
           },
           {
             title: 'Setup Keahlian Pekerja',
             url: '/list/keahlian',
             id: 10,
             parent: 303,
             enable: true,
           },
           {
             title: 'Setup Kriteria Rating Alat',
             url: '/list/j_rt_kriteria_alat',
             id: 346,
             parent: 303,
             enable: true,
           },
           {
             title: 'Setup Kriteria Rating Subkon',
             url: '/list/j_rt_kriteria_subkon',
             id: 347,
             parent: 303,
             enable: true,
           },
           {
             title: 'Setup Kriteria Rating Pekerja',
             url: '/list/j_rt_kriteria',
             id: 68,
             parent: 303,
             enable: true,
           },
           {
             title: 'Setup Jam Kerja',
             url: '/list/jam_kerja',
             id: 159,
             parent: 303,
             enable: true,
           },
           ],
         },
       {
         title: 'Bantu',
         icon: 'fa fa-question-circle',
         url: '/list/faq',
         id: '147',
         parent: -1,
         enable: true,
       },
]