/* eslint-disable no-useless-escape */
// flag 5.search, 4.delete, 3.add, 2.view, 1.list, 0.edit
// default filter : 
// {currentusername} -> current user login
// {currentuserlevel} -> current user level
// {currentuserid} -> current user id
// {currentdate} -> current Date
// {currentdateTime} -> current Date Time
// {filter=.....} -> request api with filter
// meta : field | label | viewfield | flag | align | tag | type | default 
// childselect: FldName ; FldSelectFilterFld | ..dst 
// parentselect: FldName ; FldSelectFilterFld | ..dst 
// ============================
// {login:[user attribut]} ->  user login atribut , {login:proyek_id} -> use proyek_id attribut that came with login
// flag : 11.has_child 10.has_parent 9.number, 8.primary, 7.required, 6.readonly, 5.filter, 4.search, 3.add, 2.view, 1.list, 0.edit
// link : linktablename | linkfield | displayfield1 | displayfield12 | displayfield3 | order by | asc/desc
export const model =  [
      {
          name: 'vendor',
          tablemeta : { name: 'vendor', label: 'Vendor', order: 'nama', sort: 'asc', flag: '111111',
          filter: ''   },
          columns: [
              { meta: 'id|Vendor ID|id|001110011000|left|TEXT|INT8|' },
              { meta: 'nama|Nama|nama|000010011111|left|TEXT|VARCHAR|' },
              { meta: 'alamat|Alamat|alamat|000000011101|left|TEXTAREA|VARCHAR|' },
              { meta: 'kota|Kota|kota|000000011111|left|TEXT|VARCHAR|' },
              { meta: 'kodepos|Kodepos|kodepos|000000011101|left|TEXT|VARCHAR|' },
              { meta: 'telepon|Telepon|telepon|000000011111|left|TEXT|VARCHAR|' },
              { meta: 'email|Email|email|000000011101|left|TEXT|VARCHAR|' },
              { meta: 'bank_key|Bank Key|bank_key|000000011101|left|TEXT|VARCHAR|' },
              { meta: 'npwp|NPWP|npwp|000000011101|left|TEXT|VARCHAR|' },
              { meta: 'no_rek|No Rekening|no_rek|000000011101|left|TEXT|VARCHAR|' },
              { meta: 'nama_rek|Nama Rekening|nama_rek|000000011101|left|TEXT|VARCHAR|' },
              { meta: 'na|Aktif?|na|000010011111|left|RADIO|VARCHAR|',
                tagval: '"N","Ya"|"Y","Tidak"' },
          ],
          detil: [
              { tablename: 'pembelian', detilfield: 'vendor_id', label: 'Pembelian Material',
                masterfield: 'id', icon: 'fa fa-columns' },
              { tablename: 'proyek', detilfield: 'konsumen_id', label: 'Proyek',
                masterfield: 'id', icon: 'fa fa-briefcase' },
              { tablename: 'bahan_pakai', detilfield: 'vendor_id', label: 'Pemakaian Material',
                masterfield: 'id', icon: 'fa fa-calendar' },
          ]
      },
      {
          name: 'detil_rencana',
          tablemeta : { name: 'detil_rencana', label: 'Detil Realisasi', order: 'tanggal', sort: 'asc', flag: '100110',
          filter: ''   },
          columns: [
              { meta: 'id|id|id|001110010000|left|NO|INT8|' },
              { meta: 'rencana_id|Rencana|rencana_rencana_id|001001011101|left|SELECT|INT4|',
                link: 'rencana|id|bulan_id|tahun_id||tahun_id|DESC' },
              { meta: 'tanggal|Tanggal|tanggal|002000011111|left|TEXT|DATE|' },
              { meta: 'lalu|Lalu|lalu|001000011111|left|TEXT|NUMERIC|' },
              { meta: 'target|Rencana|target|001000011111|left|TEXT|NUMERIC|' },
              { meta: 'realisasi|Realisasi|realisasi|001000011111|left|TEXT|NUMERIC|' },
              { meta: 'kumulatif|Kumulatif|kumulatif|001000011111|left|TEXT|NUMERIC|' },
              { meta: 'deviasi|Deviasi %|deviasi|001000011111|left|TEXT|NUMERIC|' },
          ],
      },
      {
          name: 'jenis_transaksi',
          tablemeta : { name: 'jenis_transaksi', label: 'Jenis pembelian', order: '', sort: '', flag: '111111',
          filter: ''   },
          columns: [
              { meta: 'id|id|id|001110010000|left|TEXT|INT4|' },
              { meta: 'nama|Nama|nama|000000011111|left|TEXT|VARCHAR|' },
          ],
          detil: [
              { tablename: 'rencana', detilfield: 'jenis_transaksi_id', label: 'Rencana',
                masterfield: 'id', icon: 'fa fa-columns' },
          ]
      },
      {
          name: 'pembelian',
          tablemeta : { name: 'pembelian', label: 'Pembelian Material', order: 'tanggal_masuk', sort: 'desc', flag: '111111',
          filter: 'filter_meta(\'plant_id\',\'pembelian.plant_id\')' ,
          autofill: { bahan_id: [ { linktable: 'vbahan', source: 'koefisien', target: 'koefisien' },
          { linktable: 'vbahan', source: 'satuan', target: 'satuan' },
          { linktable: 'vbahan', source: 'harga_satuan', target: 'harga_satuan' } ]} ,
          nested: { plant_id: [ { childfield: 'bahan_id', childid: 'plant_id', childtable: 'vbahan' },
          { childfield: 'work_center_id', childid: 'plant_id', childtable: 'work_center' } ]} },
          columns: [
              { meta: 'id|id|id|001110010000|left|NO|INT8|' },
              { meta: 'plant_id|Unit Produksi|plant_plant_id|101010111110|left|SELECT|INT4|',
                link: 'plant|id|nama|||nama|ASC',
                childselect: 'bahan_id;plant_id;vbahan|work_center_id;plant_id;work_center' },
              { meta: 'bahan_id|Bahan|vbahan_bahan_id|011010111110|left|SELECT|INT4|',
                link: 'vbahan|id|nama|satuan|smbahan_id|nama|ASC',
                parentselect: 'plant_id;plant_id|;|;|;' },
              { meta: 'tanggal_masuk|Masuk|tanggal_masuk|002010111111|left|TEXT|DATE|' },
              { meta: 'jam_masuk|Jam|jam_masuk|000010011101|left|TEXT|TIME|' },
              { meta: 'tanggal_keluar|Keluar|tanggal_keluar|002000011101|left|TEXT|DATE|' },
              { meta: 'jam_keluar|Jam|jam_keluar|000000011101|left|TEXT|TIME|' },
              { meta: 'vendor_id|Vendor|vendor_vendor_id|001010111110|left|SELECT|INT8|',
                link: 'vendor|id|nama|kota||nama|ASC' },
              { meta: 'bruto|Bruto|bruto|001000011101|left|TEXT|NUMERIC|' },
              { meta: 'netto|Netto|netto|001000011101|left|TEXT|NUMERIC|' },
              { meta: 'koefisien|Koefisien|koefisien|001000011101|left|TEXT|NUMERIC|' },
              { meta: 'volume|Volume|volume|001010011111|right|TEXT|NUMERIC|' },
              { meta: 'satuan|Satuan|satuan|000010011111|center|TEXT|VARCHAR|' },
              { meta: 'harga_satuan|Harga Sat.|harga_satuan|001000011111|right|TEXT|NUMERIC|' },
              { meta: 'jumlah|Jumlah|jumlah|001000010110|right|TEXT|FLOAT8|' },
              { meta: 'no_po|Nomer PO|no_po|000000011101|left|TEXT|VARCHAR|' },
              { meta: 'suhu|Suhu C|suhu|001000011101|left|TEXT|INT4|' },
              { meta: 'armada|No Polisi|armada|000000011101|left|TEXT|VARCHAR|' },
              { meta: 'sopir|Sopir|sopir|000000011101|left|TEXT|VARCHAR|' },
              { meta: 'tiket|Tiket|tiket|001000011101|left|TEXT|INT4|' },
              { meta: 'petugas|Petugas|petugas|000001011101|left|HIDDEN|VARCHAR|' },
              { meta: 'work_center_id|Work Center|work_center_work_center_id|011000011101|left|SELECT|INT8|',
                link: 'work_center|id|nama|||nama|ASC',
                parentselect: 'plant_id;plant_id|;|;|;' },
          ],
      },
      {
          name: 'bahan',
          tablemeta : { name: 'bahan', label: 'Material', order: 'plant_id', sort: 'asc', flag: '111111',
          filter: 'filter_meta(\'plant_id\',\'bahan.plant_id\')' ,
          autofill: { mbahan_id: [ { linktable: 'vmbahan', source: 'nama', target: 'nama' } ]}  },
          columns: [
              { meta: 'id|id|id|001110010000|left|NO|INT4|' },
              { meta: 'plant_id|Unit Produksi|plant_plant_id|001010111110|left|SELECT|INT4|',
                link: 'plant|id|nama|||nama|ASC' },
              { meta: 'mbahan_id|Bahan|vmbahan_mbahan_id|001010111110|left|SELECT|INT8|',
                link: 'vmbahan|id|nama|satuan|s_id|nama|ASC' },
              { meta: 'nama|Alias|nama|000010011111|left|TEXT|VARCHAR|' },
              { meta: 'jml_produksi|Qty Produksi|jml_produksi|001010011111|left|TEXT|NUMERIC|' },
              { meta: 'koefisien|Koefisien|koefisien|001010011111|left|TEXT|NUMERIC|' },
              { meta: 'harga_satuan|Harga Satuan|harga_satuan|001000011111|left|TEXT|NUMERIC|' },
              { meta: 'reorder_point|Reorder Point|reorder_point|001010011101|left|TEXT|NUMERIC|' },
              { meta: 'total_masuk|Masuk|total_masuk|001000000100|left|HIDDEN|NUMERIC|' },
              { meta: 'total_keluar|Keluar|total_keluar|001000000100|left|HIDDEN|NUMERIC|' },
              { meta: 'stock|Stock|stock|001010010100|left|TEXT|NUMERIC|' },
              { meta: 'jml_bahan|Jml Material|jml_bahan|001010010110|left|TEXT|INT2|' },
          ],
          detil: [
              { tablename: 'resep_produk', detilfield: 'produk_id', label: 'BoM Item',
                masterfield: 'id', icon: 'fa fa-columns' },
              { tablename: 'resep_produk', detilfield: 'bahan_id', label: 'BoM Item',
                masterfield: 'id', icon: 'fa fa-briefcase' },
              { tablename: 'kebutuhan_rencana', detilfield: 'bahan_id', label: 'Kebutuhan Material',
                masterfield: 'id', icon: 'fa fa-calendar' },
          ]
      },
      {
          name: 'rencana',
          tablemeta : { name: 'rencana', label: 'Rencana', order: 'vendor_id', sort: 'asc', flag: '111111',
          filter: 'filter_meta(\'plant_id\',\'rencana.plant_id\')' ,
          autofill: { bahan_id: [ { linktable: 'vbahan', source: 'harga_satuan', target: 'harga_satuan' },
          { linktable: 'vbahan', source: 'satuan', target: 'satuan' } ]} ,
          nested: { plant_id: [ { childfield: 'bahan_id', childid: 'plant_id', childtable: 'vbahan' } ]} },
          columns: [
              { meta: 'id|id|id|001110010100|left|NO|INT8|' },
              { meta: 'plant_id|Unit Produksi|plant_plant_id|101010111110|left|SELECT|INT4|',
                link: 'plant|id|nama|||nama|ASC',
                childselect: 'bahan_id;plant_id;vbahan' },
              { meta: 'bulan_id|Bulan|bulan_bulan_id|001010111110|left|SELECT|INT4|',
                link: 'bulan|id|nama|||id|ASC' },
              { meta: 'tahun_id|Tahun|angka_tahun_id|001010111110|left|SELECT|INT4|',
                link: 'angka|id|id|||id|ASC' },
              { meta: 'jenis_transaksi_id|Jenis|jenis_transaksi_jenis_transaksi_id|001010011100|left|HIDDEN|INT2|',
                link: 'jenis_transaksi|id|nama|||id|ASC' },
              { meta: 'vendor_id|Konsumen|konsumen_vendor_id|001000111110|left|SELECT|INT8|',
                link: 'konsumen|id|nama|||nama|ASC' },
              { meta: 'bahan_id|Bahan|vbahan_bahan_id|011010111110|left|SELECT|INT8|',
                link: 'vbahan|id|nama|satuan|smbahan_id|nama|ASC',
                parentselect: 'plant_id;plant_id|;|;|;' },
              { meta: 'volume|Volume|volume|001010011111|left|TEXT|NUMERIC|' },
              { meta: 'realisasi|Realisasi|realisasi|001000010110|left|TEXT|NUMERIC|' },
              { meta: 'harga_satuan|Harga Satuan|harga_satuan|001000011101|left|TEXT|NUMERIC|' },
              { meta: 'capaian|Capaian %|capaian|001000010110|left|TEXT|FLOAT8|' },
              { meta: 'satuan|Satuan|satuan|000010011100|left|TEXT|VARCHAR|' },
              { meta: 'rp_target|Target Rupiah|rp_target|001000010100|left|TEXT|FLOAT8|' },
              { meta: 'real_rp|Realisasi Rupiah|real_rp|001000010100|left|TEXT|FLOAT8|' },
          ],
          detil: [
              { tablename: 'detil_rencana', detilfield: 'rencana_id', label: 'Detil Realisasi',
                masterfield: 'id', icon: 'fa fa-columns' },
              { tablename: 'kebutuhan_rencana', detilfield: 'rencana_id', label: 'Kebutuhan Material',
                masterfield: 'id', icon: 'fa fa-briefcase' },
          ]
      },
      {
          name: 'jenis_kirim',
          tablemeta : { name: 'jenis_kirim', label: 'Jenis Kirim', order: '', sort: '', flag: '111111',
          filter: ''   },
          columns: [
              { meta: 'id|id|id|001110010000|left|TEXT|INT4|' },
              { meta: 'nama|Nama|nama|000000011111|left|TEXT|VARCHAR|' },
          ],
      },
      {
          name: 'plant',
          tablemeta : { name: 'plant', label: 'Unit Produksi', order: '', sort: '', flag: '101111',
          filter: 'filter_meta(\'plant_id\',\'id\')'   },
          columns: [
              { meta: 'id|Unit ID|id|001110011110|left|TEXT|INT8|' },
              { meta: 'nama|Nama|nama|000010011111|left|TEXT|VARCHAR|' },
              { meta: 'alamat|Alamat|alamat|000000011101|left|TEXTAREA|TEXT|' },
              { meta: 'kota|Kota|kota|000000011111|left|TEXT|VARCHAR|' },
              { meta: 'kodepos|Kodepos|kodepos|000000011101|left|TEXT|VARCHAR|' },
              { meta: 'petugas|Petugas|petugas|000000010100|left|TEXT|VARCHAR|' },
              { meta: 'telepon|Telepon|telepon|000000011111|left|TEXT|VARCHAR|' },
              { meta: 'keterangan|Keterangan|keterangan|000000011101|left|TEXTAREA|TEXT|' },
              { meta: 'latitude|Latitude|latitude|000010011101|left|TEXT|VARCHAR|' },
              { meta: 'longitude|Longitude|longitude|000010011101|left|TEXT|VARCHAR|' },
              { meta: 'foto|Foto|foto|000010011111|left|FILE|TEXT|',
              file: { enable: '1', path: '\"./custom/upload/plant/foto/\"', multi: '0' } },
          ],
          detil: [
              { tablename: 'pembelian', detilfield: 'plant_id', label: 'Pembelian Material',
                masterfield: 'id', icon: 'fa fa-columns' },
              { tablename: 'bahan', detilfield: 'plant_id', label: 'Material',
                masterfield: 'id', icon: 'fa fa-cube' },
              { tablename: 'rencana', detilfield: 'plant_id', label: 'Rencana',
                masterfield: 'id', icon: 'fa fa-calendar' },
              { tablename: 'users', detilfield: 'plant_id', label: 'Pengguna',
                masterfield: 'id', icon: 'fa fa-list-alt' },
              { tablename: 'masalah', detilfield: 'plant_id', label: 'Masalah',
                masterfield: 'id', icon: 'fa fa-industry' },
              { tablename: 'bahan_pakai', detilfield: 'plant_id', label: 'Pemakaian Material',
                masterfield: 'id', icon: 'fa fa-table' },
              { tablename: 'resep_produk', detilfield: 'plant_id', label: 'BoM Item',
                masterfield: 'id', icon: 'fa fa-file' },
              { tablename: 'vbahan', detilfield: 'plant_id', label: 'vbahan',
                masterfield: 'id', icon: 'fa fa-columns' },
              { tablename: 'work_center', detilfield: 'plant_id', label: 'Work Center',
                masterfield: 'id', icon: 'fa fa-briefcase' },
              { tablename: 'penjualan', detilfield: 'plant_id', label: 'Realisasi',
                masterfield: 'id', icon: 'fa fa-calendar' },
          ]
      },
      {
          name: 'kategori_bahan',
          tablemeta : { name: 'kategori_bahan', label: 'Kategori BoM', order: '', sort: '', flag: '111111',
          filter: ''   },
          columns: [
              { meta: 'id|id|id|001110010000|left|NO|INT4|' },
              { meta: 'nama|Nama|nama|000000011111|left|TEXT|VARCHAR|' },
              { meta: 'na|Aktif?|na|000000011111|left|SELECT|BPCHAR|',
                tagval: '"N","Ya"|"Y","Tidak"' },
          ],
          detil: [
              { tablename: 'mbahan', detilfield: 'kategori_id', label: 'Master Bahan',
                masterfield: 'id', icon: 'fa fa-columns' },
              { tablename: 'vmbahan', detilfield: 'kategori_id', label: 'vmbahan',
                masterfield: 'id', icon: 'fa fa-briefcase' },
          ]
      },
      {
          name: 'proyek',
          tablemeta : { name: 'proyek', label: 'Proyek', order: 'nama', sort: 'asc', flag: '111111',
          filter: 'filtermeta(\'plant_id\',\'plant_id\')'   },
          columns: [
              { meta: 'id|id|id|001110010000|left|NO|INT8|' },
              { meta: 'plant_id|Unit Produksi|plant_id|001010011111|left|TEXT|INT8|' },
              { meta: 'konsumen_id|Konsumen|vendor_konsumen_id|001001111111|left|SELECT|INT8|',
                link: 'vendor|id|nama|||nama|ASC' },
              { meta: 'nama|Nama|nama|000000011111|left|TEXT|VARCHAR|' },
              { meta: 'na|Aktif?|na|000000011111|left|SELECT|BPCHAR|',
                tagval: '"N","Ya"|"Y","Tidak"' },
          ],
          detil: [
              { tablename: 'penjualan', detilfield: 'proyek_id', label: 'Realisasi',
                masterfield: 'id', icon: 'fa fa-columns' },
          ]
      },
      {
          name: 'userlevelpermissions',
          tablemeta : { name: 'userlevelpermissions', label: 'Hak Akses', order: '', sort: '', flag: '111111',
          filter: ''   },
          columns: [
              { meta: 'userlevels_id|Level|userlevels_id|001010011111|left|TEXT|INT8|' },
              { meta: 'tablename|Nama Table|tablename|000110011111|left|TEXT|VARCHAR|' },
              { meta: 'permission|Hak Akses|permission|001010011111|left|TEXT|INT8|' },
          ],
      },
      {
          name: 'userlevels',
          tablemeta : { name: 'userlevels', label: 'Level Pengguna', order: '', sort: '', flag: '111111',
          filter: ''   },
          columns: [
              { meta: 'id|id|id|001110011111|left|TEXT|INT8|' },
              { meta: 'nama|Nama Level|nama|000010011111|left|TEXT|VARCHAR|' },
          ],
          detil: [
              { tablename: 'users', detilfield: 'userlevels_id', label: 'Pengguna',
                masterfield: 'id', icon: 'fa fa-columns' },
          ]
      },
      {
          name: 'users',
          tablemeta : { name: 'users', label: 'Pengguna', order: '', sort: '', flag: '111111',
          filter: 'filter_meta(\'id\',\'id\')'   },
          columns: [
              { meta: 'id|id|id|001110010000|left|NO|INT4|' },
              { meta: 'username|Username|username|000010011110|left|TEXT|VARCHAR|' },
              { meta: 'fullname|Nama Lengkap|fullname|000010011111|left|TEXT|VARCHAR|' },
              { meta: 'email|Email|email|000000011111|left|TEXT|VARCHAR|' },
              { meta: 'telepon|Telepon|telepon|000000011111|left|TEXT|VARCHAR|' },
              { meta: 'nip|NIP|nip|000000011111|left|TEXT|VARCHAR|' },
              { meta: 'password|Password|password|000000011101|left|PASSWORD|VARCHAR|' },
              { meta: 'userlevels_id|Level|userlevels_userlevels_id|0010000|left|SELECT|INT8|',
                link: 'userlevels|id|nama||||' },
              { meta: 'plant_id|Unit Produksi|plant_plant_id|0000000|left|CHECKBOX|TEXT|',
                link: 'plant|id|nama|||nama|ASC' },
              { meta: 'off_notification|Matikan Notif|jenis_notifikasi_off_notification|000010011111|left|CHECKBOX|VARCHAR|',
                link: 'jenis_notifikasi|nama|tampilan|||nama|ASC' },
              { meta: 'na|Aktif?|na|0000100|left|SELECT|VARCHAR|',
                tagval: '"N","Ya"|"Y","Tidak"' },
              { meta: 'foto|Foto|foto|000000011111|left|FILE|VARCHAR|',
              file: { enable: '1', path: '\"./custom/upload/users/foto/\"', multi: '0' } },
          ],
          detil: [
              { tablename: 'pesan', detilfield: 'tujuan', label: 'Pesan',
                masterfield: 'username', icon: 'fa fa-comments' },
          ]
      },
      {
          name: 'bulan',
          tablemeta : { name: 'bulan', label: 'bulan', order: '', sort: '', flag: '111111',
          filter: ''   },
          columns: [
              { meta: 'id|id|id|001110011111|left|TEXT|INT4|' },
              { meta: 'nama|nama|nama|000010011111|left|TEXT|VARCHAR|' },
          ],
          detil: [
              { tablename: 'rencana', detilfield: 'bulan_id', label: 'Rencana',
                masterfield: 'id', icon: 'fa fa-columns' },
          ]
      },
      {
          name: 'angka',
          tablemeta : { name: 'angka', label: 'angka', order: '', sort: '', flag: '111111',
          filter: ''   },
          columns: [
              { meta: 'id|id|id|001110011111|left|TEXT|INT4|' },
              { meta: 'nama|nama|nama|001000011111|left|TEXT|VARCHAR|' },
          ],
      },
      {
          name: 'masalah',
          tablemeta : { name: 'masalah', label: 'Masalah', order: 'tanggal', sort: 'desc', flag: '111111',
          filter: 'filter_meta(\'plant_id\',\'masalah.plant_id\')'   },
          columns: [
              { meta: 'id|id|id|001110010000|left|NO|INT4|' },
              { meta: 'pesan|Pesan|pesan|000000010100|left|TEXTAREA|TEXT|' },
              { meta: 'judul|Judul|judul|000010011110|left|TEXTAREA|VARCHAR|' },
              { meta: 'plant_id|Unit Produksi|plant_plant_id|001000111110|left|SELECT|INT4|',
                link: 'plant|id|nama|||nama|ASC' },
              { meta: 'tanggal|Tanggal|tanggal|002000011110|left|HIDDEN|DATE|' },
              { meta: 'jam|jam|jam|000010011110|left|HIDDEN|TIME|' },
              { meta: 'keterangan|Penjelasan|keterangan|000000011101|left|TEXTAREA|TEXT|' },
              { meta: 'status_masalah_id|Status|status_masalah_status_masalah_id|001000110111|left|SELECT|INT4|',
                link: 'status_masalah|id|nama|||id|ASC' },
              { meta: 'username|Petugas|username|000000011100|left|HIDDEN|VARCHAR|' },
              { meta: 'foto|Foto|foto|000000011110|left|FILE|TEXT|',
              file: { enable: '1', path: '\"./custom/upload/masalah/foto/\"', multi: '0' } },
          ],
          detil: [
              { tablename: 'tindak_lanjut', detilfield: 'masalah_id', label: 'Tindak Lanjut',
                masterfield: 'id', icon: 'fa fa-columns' },
              { tablename: 'komentar', detilfield: 'masalah_id', label: 'Komentar',
                masterfield: 'id', icon: 'fa fa-briefcase' },
          ]
      },
      {
          name: 'tindak_lanjut',
          tablemeta : { name: 'tindak_lanjut', label: 'Tindak Lanjut', order: '', sort: '', flag: '111111',
          filter: ''   },
          columns: [
              { meta: 'id|id|id|001110010000|left|NO|INT4|' },
              { meta: 'masalah_id|Masalah|masalah_masalah_id|001010011101|left|HIDDEN|INT8|',
                link: 'masalah|id|tanggal|judul||tanggal|DESC' },
              { meta: 'tanggal|Tanggal|tanggal|002010011111|left|HIDDEN|DATE|' },
              { meta: 'jam|Jam|jam|000010011111|left|HIDDEN|TIME|' },
              { meta: 'uraian|Pesan|uraian|000010011111|left|TEXTAREA|TEXT|' },
              { meta: 'username|Username|username|000010011111|left|HIDDEN|VARCHAR|' },
              { meta: 'status_masalah_id|Status|status_masalah_status_masalah_id|001010011111|left|SELECT|INT2|',
                link: 'status_masalah|id|nama|||id|ASC' },
              { meta: 'foto|Foto|foto|000000011111|left|FILE|TEXT|',
              file: { enable: '1', path: '\"./custom/upload/tindak_lanjut/foto/\"', multi: '0' } },
          ],
      },
      {
          name: 'jenis_notifikasi',
          tablemeta : { name: 'jenis_notifikasi', label: 'jenis notifikasi', order: '', sort: '', flag: '111111',
          filter: ''   },
          columns: [
              { meta: 'id|id|id|001110010000|left|NO|INT4|' },
              { meta: 'nama|Nama|nama|000011011111|left|TEXT|VARCHAR|' },
              { meta: 'tampilan|Tampilan|tampilan|000000011111|left|TEXT|VARCHAR|' },
              { meta: 'na|Aktif?|na|000010011111|left|SELECT|BPCHAR|',
                tagval: '"N","Ya"|"Y","Tidak"' },
          ],
          detil: [
              { tablename: 'users', detilfield: 'off_notification', label: 'Pengguna',
                masterfield: 'nama', icon: 'fa fa-columns' },
          ]
      },
      {
          name: 'pesan',
          tablemeta : { name: 'pesan', label: 'Pesan', order: 'tujuan', sort: 'asc', flag: '111110',
          filter: '" pengirim=\'".CurrentUserName()."\' or tujuan=\'".CurrentUserName()."\'"'   },
          columns: [
              { meta: 'id|id|id|001110010000|left|NO|INT4|' },
              { meta: 'tanggal|Tanggal|tanggal|002010011100|left|HIDDEN|DATE|' },
              { meta: 'jam|Jam|jam|002010011100|left|HIDDEN|TIME|' },
              { meta: 'pengirim|Pengirim|pengirim|000010011110|left|HIDDEN|VARCHAR|' },
              { meta: 'tujuan|Tujuan|users_tujuan|000010111110|left|TEXT|VARCHAR|',
                link: 'users|username|fullname|||fullname|ASC' },
              { meta: 'pesan|Pesan|pesan|000000010100|left|TEXTAREA|TEXT|' },
              { meta: 'judul|Judul|judul|000010011100|left|TEXT|VARCHAR|' },
              { meta: 'isi|Isi|isi|000000011100|left|TEXTAREA|TEXT|' },
              { meta: 'status|Status|status|0010100|left|SELECT|INT2|',
                tagval: '"0","Submited"|"1","Sent"|"2","Read"' },
          ],
      },
      {
          name: 'faq',
          tablemeta : { name: 'faq', label: 'Bantu', order: '', sort: '', flag: '111111',
          filter: ''   },
          columns: [
              { meta: 'id|id|id|001110010000|left|NO|INT4|' },
              { meta: 'tipe|App|tipe|001010011111|left|SELECT|INT2|',
                tagval: '"1","WEB"|"2","MOBILE"' },
              { meta: 'pertanyaan|Pertanyaan|pertanyaan|000010011111|left|TEXTAREA|VARCHAR|' },
              { meta: 'jawaban|Jawaban|jawaban|000000011111|left|TEXTAREA|TEXT|' },
              { meta: 'file|File|file|000000011111|left|FILE|TEXT|',
              file: { enable: '1', path: '\"./custom/upload/faq/file/\"', multi: '0' } },
          ],
      },
      {
          name: 'banner',
          tablemeta : { name: 'banner', label: 'Banner', order: '', sort: '', flag: '111111',
          filter: ''   },
          columns: [
              { meta: 'id|id|id|001110010000|left|NO|INT4|' },
              { meta: 'teks|Teks|teks|000000011111|left|TEXT|VARCHAR|' },
              { meta: 'na|Aktif?|na|000010011111|left|SELECT|BPCHAR|',
                tagval: '"N","Ya"|"Y","Tidak"' },
              { meta: 'gambar|Gambar 640x250|gambar|000010011111|left|FILE|TEXT|',
              file: { enable: '1', path: '\"./custom/upload/banner/gambar/\"', multi: '0' } },
          ],
      },
      {
          name: 'bahan_pakai',
          tablemeta : { name: 'bahan_pakai', label: 'Pemakaian Material', order: 'jam', sort: 'asc', flag: '111111',
          filter: 'filter_meta(\'plant_id\',\'bahan_pakai.plant_id\')'  ,
          nested: { plant_id: [ { childfield: 'bahan_id', childid: 'plant_id', childtable: 'vbahan' },
          { childfield: 'produk_id', childid: 'plant_id', childtable: 'vbahan' } ]} },
          columns: [
              { meta: 'id|id|id|001110010100|left|NO|INT4|' },
              { meta: 'plant_id|Unit Produksi|plant_plant_id|101011111111|left|SELECT|INT4|',
                link: 'plant|id|nama|||nama|ASC',
                childselect: 'bahan_id;plant_id;vbahan|produk_id;plant_id;vbahan' },
              { meta: 'bahan_id|Bahan|vbahan_bahan_id|011011111111|left|SELECT|INT4|',
                link: 'vbahan|id|nama|smbahan_id||nama|ASC',
                parentselect: 'plant_id;plant_id|;|;|;' },
              { meta: 'vendor_id|Vendor|vendor_vendor_id|001000011111|left|SELECT|INT8|',
                link: 'vendor|id|nama|||nama|ASC' },
              { meta: 'produk_id|Untuk Produk|vbahan_produk_id|011001111111|left|SELECT|INT4|',
                link: 'vbahan|id|nama|smbahan_id||nama|ASC',
                parentselect: 'plant_id;plant_id|;|;|;' },
              { meta: 'volume|Volume|volume|001010011111|left|TEXT|NUMERIC|' },
              { meta: 'harga_satuan|Harga Satuan|harga_satuan|001000011111|left|HIDDEN|NUMERIC|' },
              { meta: 'satuan|Satuan|satuan|000011011111|left|TEXT|VARCHAR|' },
              { meta: 'tanggal|Tanggal|tanggal|002010011111|left|TEXT|DATE|' },
              { meta: 'jam|Jam|jam|000010011111|left|TEXT|TIME|' },
              { meta: 'penerima|Penerima|penerima|000010011110|left|TEXT|VARCHAR|' },
              { meta: 'petugas|Petugas|petugas|001010011110|left|HIDDEN|VARCHAR|' },
          ],
      },
      {
          name: 'resep_produk',
          tablemeta : { name: 'resep_produk', label: 'BoM Item', order: 'bahan_id', sort: 'asc', flag: '111111',
          filter: '' ,
          autofill: { bahan_id: [ { linktable: 'bahan', source: 'harga_satuan', target: 'harga_satuan' },
          { linktable: 'bahan', source: 'mbahan_id', target: 'mbahan_id' } ]} ,
          nested: { plant_id: [ { childfield: 'bahan_id', childid: 'plant_id', childtable: 'bahan' } ]} },
          columns: [
              { meta: 'id|id|id|001110010000|left|NO|INT8|' },
              { meta: 'mproduk_id|No Mat Prod|mproduk_id|001010011100|left|HIDDEN|INT8|' },
              { meta: 'produk_id|Produk|bahan_produk_id|001010111110|left|TEXT|INT8|',
                link: 'bahan|id|nama|mbahan_id||nama|ASC' },
              { meta: 'plant_id|UP|plant_plant_id|101010011110|left|TEXT|INT4|',
                link: 'plant|id|nama|||nama|ASC',
                childselect: 'bahan_id;plant_id;bahan' },
              { meta: 'mbahan_id|No Mat bahan|mbahan_id|001010011100|left|HIDDEN|INT8|' },
              { meta: 'bahan_id|Bahan|bahan_bahan_id|011010111110|left|SELECT|INT8|',
                link: 'bahan|id|nama|mbahan_id||nama|ASC',
                parentselect: 'plant_id;plant_id|;|;|;' },
              { meta: 'volume|Qty. Komponen|volume|001000011111|left|TEXT|NUMERIC|' },
              { meta: 'volume_out|Base Qty|volume_out|001010011111|left|TEXT|NUMERIC|' },
              { meta: 'qty_prod|Qty / Produksi|qty_prod|001000010110|left|TEXT|FLOAT8|' },
              { meta: 'harga_satuan|Harga Satuan|harga_satuan|001010011111|left|TEXT|NUMERIC|' },
          ],
      },
      {
          name: 'notifikasi',
          tablemeta : { name: 'notifikasi', label: 'Notifikasi', order: 'username', sort: 'asc', flag: '100010',
          filter: '"username=\'".CurrentUserName()."\' and status<=0 "'   },
          columns: [
              { meta: 'id|id|id|001110010000|left|NO|INT4|' },
              { meta: 'pilih|Pilih|pilih|0000000|left|TEXTAREA|TEXT|' },
              { meta: 'tanggal|Tanggal|tanggal|002010011001|left|TEXT|DATE|' },
              { meta: 'jam|Jam|jam|000010011001|left|TEXT|TIME|' },
              { meta: 'isi|Isi|isi|000000011001|left|TEXTAREA|TEXT|' },
              { meta: 'nama_tabel|Tabel|nama_tabel|000010011001|left|TEXT|VARCHAR|' },
              { meta: 'id_tabel|id|id_tabel|001010011001|left|TEXT|INT8|' },
              { meta: 'username|Username|username|000010011001|left|TEXT|VARCHAR|' },
              { meta: 'pesan|Pesan|pesan|000000011111|left|TEXTAREA|TEXT|' },
              { meta: 'status|Dibaca|status|001010011001|left|TEXT|INT2|' },
              { meta: 'url|URL|url|000000010000|left|TEXTAREA|TEXT|' },
          ],
      },
      {
          name: 'audittrail',
          tablemeta : { name: 'audittrail', label: 'Audit trail', order: '', sort: '', flag: '111111',
          filter: ''   },
          columns: [
              { meta: 'id|id|id|001110010111|left|NO|INT4|' },
              { meta: 'tanggal|tanggal|tanggal|002010011111|left|TEXT|TIMESTAMP|' },
              { meta: 'script|script|script|000000011111|left|TEXT|VARCHAR|' },
              { meta: 'pengguna|pengguna|pengguna|000000011111|left|TEXT|VARCHAR|' },
              { meta: 'aksi|aksi|aksi|000000011111|left|TEXT|VARCHAR|' },
              { meta: 'tabel|tabel|tabel|000000011111|left|TEXT|VARCHAR|' },
              { meta: 'kolom|kolom|kolom|000000011111|left|TEXT|VARCHAR|' },
              { meta: 'nilai|nilai|nilai|000000011101|left|TEXTAREA|TEXT|' },
              { meta: 'nilai_lama|nilai lama|nilai_lama|000000011101|left|TEXTAREA|TEXT|' },
              { meta: 'nilai_baru|nilai baru|nilai_baru|000000011101|left|TEXTAREA|TEXT|' },
          ],
      },
      {
          name: 'mbahan',
          tablemeta : { name: 'mbahan', label: 'Master Bahan', order: '', sort: '', flag: '111111',
          filter: ''   },
          columns: [
              { meta: 'id|No. Material|id|001110111110|left|TEXT|INT8|' },
              { meta: 'nama|Nama|nama|000010011111|left|TEXT|VARCHAR|' },
              { meta: 'kategori_id|Kategori|kategori_bahan_kategori_id|001010111111|left|SELECT|INT4|',
                link: 'kategori_bahan|id|nama|||nama|ASC' },
              { meta: 'satuan|Satuan|satuan|000010011111|left|TEXT|VARCHAR|' },
              { meta: 'na|Aktif ?|na|000010111111|left|SELECT|BPCHAR|',
                tagval: '"N","Ya"|"Y","Tidak"' },
          ],
          detil: [
              { tablename: 'vbahan', detilfield: 'mbahan_id', label: 'vbahan',
                masterfield: 'id', icon: 'fa fa-columns' },
          ]
      },
      {
          name: 'konsumen',
          tablemeta : { name: 'konsumen', label: 'Konsumen', order: 'nama', sort: 'asc', flag: '111111',
          filter: ''   },
          columns: [
              { meta: 'id|id|id|001110010100|left|NO|INT8|' },
              { meta: 'nama|Nama|nama|000010011111|left|TEXT|VARCHAR|' },
              { meta: 'alamat|Alamat|alamat|000000011101|left|TEXT|VARCHAR|' },
              { meta: 'kota|Kota|kota|000000011111|left|TEXT|VARCHAR|' },
              { meta: 'kodepos|Kodepos|kodepos|000000011101|left|TEXT|VARCHAR|' },
              { meta: 'telepon|Telepon|telepon|000000011101|left|TEXT|VARCHAR|' },
              { meta: 'email|Email|email|000000011111|left|TEXT|VARCHAR|' },
              { meta: 'bank_key|Bank Key|bank_key|000000011101|left|TEXT|VARCHAR|' },
              { meta: 'npwp|NPWP|npwp|000000011101|left|TEXT|VARCHAR|' },
              { meta: 'no_rek|No Rekening|no_rek|000000011101|left|TEXT|VARCHAR|' },
              { meta: 'nama_rek|Nama Rekening|nama_rek|000000011101|left|TEXT|VARCHAR|' },
              { meta: 'na|Aktif ?|na|000010011111|left|RADIO|VARCHAR|',
                tagval: '"N","Ya"|"Y","Tidak"' },
          ],
          detil: [
              { tablename: 'rencana', detilfield: 'vendor_id', label: 'Rencana',
                masterfield: 'id', icon: 'fa fa-columns' },
              { tablename: 'penjualan', detilfield: 'vendor_id', label: 'Realisasi',
                masterfield: 'id', icon: 'fa fa-briefcase' },
          ]
      },
      {
          name: 'vbahan',
          tablemeta : { name: 'vbahan', label: 'vbahan', order: '', sort: '', flag: '100010',
          filter: '' ,
          autofill: { mbahan_id: [ { linktable: 'mbahan', source: 'nama', target: 'nama' } ]}  },
          columns: [
              { meta: 'id|id|id|001100010000|left|NO|INT4|' },
              { meta: 'plant_id|Unit Produksi|plant_plant_id|001000111110|left|SELECT|INT4|',
                link: 'plant|id|nama|||nama|ASC' },
              { meta: 'mbahan_id|Bahan|mbahan_mbahan_id|001000111110|left|SELECT|INT8|',
                link: 'mbahan|id|nama|id||nama|ASC' },
              { meta: 'nama|Alias|nama|000000011111|left|TEXT|VARCHAR|' },
              { meta: 'jml_produksi|Qty Produksi|jml_produksi|001000011111|left|TEXT|NUMERIC|' },
              { meta: 'koefisien|Koefisien|koefisien|001000011101|left|TEXT|NUMERIC|' },
              { meta: 'harga_satuan|Harga Satuan|harga_satuan|001000011101|left|TEXT|NUMERIC|' },
              { meta: 'reorder_point|Reorder Point|reorder_point|001000011101|left|TEXT|NUMERIC|' },
              { meta: 'total_masuk|Masuk|total_masuk|001000000110|left|HIDDEN|NUMERIC|' },
              { meta: 'total_keluar|Keluar|total_keluar|001000000110|left|HIDDEN|NUMERIC|' },
              { meta: 'stock|Stock|stock|001000010100|left|TEXT|NUMERIC|' },
              { meta: 'smbahan_id|smbahan id|smbahan_id|000000011111|left|TEXT|VARCHAR|' },
              { meta: 'satuan|satuan|satuan|000000011111|left|TEXT|VARCHAR|' },
          ],
          detil: [
              { tablename: 'pembelian', detilfield: 'bahan_id', label: 'Pembelian Material',
                masterfield: 'id', icon: 'fa fa-columns' },
              { tablename: 'rencana', detilfield: 'bahan_id', label: 'Rencana',
                masterfield: 'id', icon: 'fa fa-briefcase' },
              { tablename: 'bahan_pakai', detilfield: 'bahan_id', label: 'Pemakaian Material',
                masterfield: 'id', icon: 'fa fa-calendar' },
              { tablename: 'bahan_pakai', detilfield: 'produk_id', label: 'Pemakaian Material',
                masterfield: 'id', icon: 'fa fa-list-alt' },
              { tablename: 'penjualan', detilfield: 'bahan_id', label: 'Realisasi',
                masterfield: 'id', icon: 'fa fa-industry' },
              { tablename: 'vkebutuhan_bahan', detilfield: 'bahan_id', label: 'Kebutuhan Material',
                masterfield: 'id', icon: 'fa fa-table' },
          ]
      },
      {
          name: 'vmbahan',
          tablemeta : { name: 'vmbahan', label: 'vmbahan', order: '', sort: '', flag: '100010',
          filter: ''   },
          columns: [
              { meta: 'id|No. Material|id|001100111110|left|TEXT|INT8|' },
              { meta: 'nama|Nama|nama|000000011111|left|TEXT|VARCHAR|' },
              { meta: 'kategori_id|Kategori|kategori_bahan_kategori_id|001000111111|left|SELECT|INT4|',
                link: 'kategori_bahan|id|nama|||nama|ASC' },
              { meta: 'satuan|Satuan|satuan|000000011111|left|TEXT|VARCHAR|' },
              { meta: 'na|Aktif ?|na|000000011111|left|RADIO|BPCHAR|',
                tagval: '"N","Ya"|"Y","Tidak"' },
              { meta: 's_id|s id|s_id|000000011111|left|TEXT|VARCHAR|' },
          ],
          detil: [
              { tablename: 'bahan', detilfield: 'mbahan_id', label: 'Material',
                masterfield: 'id', icon: 'fa fa-cube' },
          ]
      },
      {
          name: 'work_center',
          tablemeta : { name: 'work_center', label: 'Work Center', order: 'nama', sort: 'asc', flag: '111111',
          filter: 'filter_meta(\'plant_id\',\'work_Center.plant_id\')'   },
          columns: [
              { meta: 'id|ID|id|001110010101|left|NO|INT4|' },
              { meta: 'plant_id|Unit Produksi|plant_plant_id|001010111111|left|SELECT|INT8|',
                link: 'plant|id|nama|id|||' },
              { meta: 'nama|Nama|nama|000010011111|left|TEXT|VARCHAR|' },
              { meta: 'kode|Kode|kode|000010011111|left|TEXT|VARCHAR|' },
              { meta: 'jam_mulai|Jam Mulai|jam_mulai|000010011111|left|TEXT|TIME|' },
              { meta: 'jam_selesai|Jam Selesai|jam_selesai|000010011111|left|TEXT|TIME|' },
              { meta: 'istirahat|Istirahat|istirahat|000010011111|left|TEXT|TIME|' },
              { meta: 'kapasitas|Kapasitas|angka_kapasitas|001010011111|left|SELECT|NUMERIC|',
                link: 'angka|id|id|nama||id|ASC',
                tagval: '"",""' },
              { meta: 'jml_mesin|Jml Mesin|jml_mesin|001010011111|left|SELECT|INT2|',
                tagval: '"1","1"|"2","2"|"3","3"|"4","4"|"5","5"' },
          ],
          detil: [
              { tablename: 'pembelian', detilfield: 'work_center_id', label: 'Pembelian Material',
                masterfield: 'id', icon: 'fa fa-columns' },
              { tablename: 'penjualan', detilfield: 'work_center_id', label: 'Realisasi',
                masterfield: 'id', icon: 'fa fa-briefcase' },
          ]
      },
      {
          name: 'penjualan',
          tablemeta : { name: 'penjualan', label: 'Realisasi', order: 'tanggal_masuk', sort: 'desc', flag: '111111',
          filter: 'filter_meta(\'plant_id\',\'penjualan.plant_id\')' ,
          autofill: { bahan_id: [ { linktable: 'vbahan', source: 'koefisien', target: 'koefisien' },
          { linktable: 'vbahan', source: 'satuan', target: 'satuan' },
          { linktable: 'vbahan', source: 'harga_satuan', target: 'harga_satuan' } ]} ,
          nested: { plant_id: [ { childfield: 'bahan_id', childid: 'plant_id', childtable: 'vbahan' },
          { childfield: 'proyek_id', childid: 'plant_id', childtable: 'proyek' },
          { childfield: 'work_center_id', childid: 'plant_id', childtable: 'work_center' } ]} },
          columns: [
              { meta: 'id|id|id|001110010000|left|NO|INT8|' },
              { meta: 'plant_id|Unit Produksi|plant_plant_id|101010111110|left|SELECT|INT4|',
                link: 'plant|id|nama|||nama|ASC',
                childselect: 'bahan_id;plant_id;vbahan|proyek_id;plant_id;proyek|work_center_id;plant_id;work_center' },
              { meta: 'bahan_id|Bahan|vbahan_bahan_id|011010111110|left|SELECT|INT4|',
                link: 'vbahan|id|nama|satuan|smbahan_id|nama|ASC',
                parentselect: 'plant_id;plant_id|;|;|;' },
              { meta: 'tanggal_masuk|Tanggal|tanggal_masuk|002010111111|left|TEXT|DATE|' },
              { meta: 'jam_masuk|Jam|jam_masuk|000010011101|left|TEXT|TIME|' },
              { meta: 'vendor_id|Konsumen|konsumen_vendor_id|001010111110|left|SELECT|INT8|',
                link: 'konsumen|id|nama|kota||nama|ASC' },
              { meta: 'proyek_id|Proyek/Lokasi|proyek_proyek_id|011000111100|left|SELECT|INT4|',
                link: 'proyek|id|nama|||nama|ASC',
                parentselect: 'plant_id;plant_id|vendor_id;konsumen_id|;|;' },
              { meta: 'bruto|Bruto|bruto|001000011101|left|TEXT|NUMERIC|' },
              { meta: 'netto|Netto|netto|001000011101|left|TEXT|NUMERIC|' },
              { meta: 'koefisien|Koefisien|koefisien|001000011101|left|TEXT|NUMERIC|' },
              { meta: 'volume|Volume|volume|001010011111|right|TEXT|NUMERIC|' },
              { meta: 'satuan|Satuan|satuan|000010011111|center|TEXT|VARCHAR|' },
              { meta: 'harga_satuan|Harga Sat.|harga_satuan|001000011111|right|TEXT|NUMERIC|' },
              { meta: 'jumlah|Jumlah|jumlah|001000010110|right|TEXT|FLOAT8|' },
              { meta: 'petugas|Petugas|petugas|000001011101|left|HIDDEN|VARCHAR|' },
              { meta: 'work_center_id|Work Center|work_center_work_center_id|011000011101|left|SELECT|INT8|',
                link: 'work_center|id|nama|||nama|ASC',
                parentselect: 'plant_id;plant_id|;|;|;' },
          ],
      },
      {
          name: 'status_masalah',
          tablemeta : { name: 'status_masalah', label: 'Status Masalah', order: '', sort: '', flag: '111111',
          filter: ''   },
          columns: [
              { meta: 'id|id|id|001110010111|left|NO|INT4|' },
              { meta: 'nama|nama|nama|000010011111|left|TEXT|VARCHAR|' },
              { meta: 'warna|warna|warna|000010011111|left|TEXT|VARCHAR|' },
          ],
          detil: [
              { tablename: 'masalah', detilfield: 'status_masalah_id', label: 'Masalah',
                masterfield: 'id', icon: 'fa fa-columns' },
              { tablename: 'tindak_lanjut', detilfield: 'status_masalah_id', label: 'Tindak Lanjut',
                masterfield: 'id', icon: 'fa fa-briefcase' },
          ]
      },
      {
          name: 'komentar',
          tablemeta : { name: 'komentar', label: 'Komentar', order: '', sort: '', flag: '111111',
          filter: ''   },
          columns: [
              { meta: 'id|id|id|001110010000|left|NO|INT4|' },
              { meta: 'masalah_id|Masalah|masalah_masalah_id|001010011110|left|HIDDEN|INT8|',
                link: 'masalah|id|judul|tanggal|jam|judul|ASC' },
              { meta: 'username|Pengguna|username|000010011111|left|HIDDEN|VARCHAR|' },
              { meta: 'tanggal|Tanggal|tanggal|002010011110|left|HIDDEN|DATE|' },
              { meta: 'jam|Jam|jam|000010011110|left|HIDDEN|TIME|' },
              { meta: 'pesan|Pesan|pesan|000010011101|left|TEXTAREA|TEXT|' },
          ],
      },
      {
          name: 'kebutuhan_rencana',
          tablemeta : { name: 'kebutuhan_rencana', label: 'Kebutuhan Material', order: '', sort: '', flag: '111111',
          filter: ''   },
          columns: [
              { meta: 'id|id|id|001110010000|left|NO|INT4|' },
              { meta: 'rencana_id|Rencana|rencana_rencana_id|001010011000|left|SELECT|INT8|',
                link: 'rencana|id|bulan_id|tahun_id||bahan_id|ASC' },
              { meta: 'bahan_id|Bahan|bahan_bahan_id|001010011110|left|SELECT|INT8|',
                link: 'bahan|id|nama|mbahan_id||nama|ASC' },
              { meta: 'volume|Volume|volume|001010011111|left|TEXT|NUMERIC|' },
              { meta: 'level|Level|level|001010011110|left|TEXT|INT2|' },
          ],
      },
      {
          name: 'vkebutuhan_bahan',
          tablemeta : { name: 'vkebutuhan_bahan', label: 'Kebutuhan Material', order: '', sort: '', flag: '100010',
          filter: ''   },
          columns: [
              { meta: 'bahan_id|Bahan|vbahan_bahan_id|001100011001|left|SELECT|INT8|',
                link: 'vbahan|id|nama|satuan|mbahan_id|nama|ASC' },
              { meta: 'nama|Bahan|nama|000000011111|left|TEXT|VARCHAR|' },
              { meta: 'volume|Total Kebutuhan|volume|001000011011|left|TEXT|NUMERIC|' },
              { meta: 'stock|Stock Tersedia|stock|001000011111|left|TEXT|NUMERIC|' },
              { meta: 'realisasi|Realisasi|realisasi|001000011001|left|TEXT|NUMERIC|' },
              { meta: 'capaian|Capaian|capaian|001000011111|left|TEXT|NUMERIC|' },
              { meta: 'digunakan|Digunakan|digunakan|001000011111|left|TEXT|NUMERIC|' },
              { meta: 'kebutuhan|Kebutuhan|kebutuhan|001000011111|left|TEXT|NUMERIC|' },
              { meta: 'kekurangan|Kekurangan Stock|kekurangan|001000011111|left|TEXT|NUMERIC|' },
              { meta: 'rencana_id|rencana id|rencana_id|001000011001|left|TEXT|INT8|' },
              { meta: 'level|Level|level|001000011111|left|TEXT|INT2|' },
          ],
      },
  ];